# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate xmlparser

Name:           rust-%{crate}
Version:        0.1.2
Release:        1%{?dist}
Summary:        Pull-based, zero-allocation XML parser

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/xmlparser
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(error-chain) >= 0.11.0 with crate(error-chain) < 0.12.0)
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0)
%if %{with check}
BuildRequires:  (crate(rustc-test/default) >= 0.2.0 with crate(rustc-test/default) < 0.3.0)
BuildRequires:  (crate(serde/default) >= 1.0.0 with crate(serde/default) < 2.0.0)
BuildRequires:  (crate(serde_derive/default) >= 1.0.0 with crate(serde_derive/default) < 2.0.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.0 with crate(serde_json/default) < 2.0.0)
BuildRequires:  (crate(stderrlog/default) >= 0.2.0 with crate(stderrlog/default) < 0.3.0)
%endif
%endif

%global _description %{expand:
Pull-based, zero-allocation XML parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 00:57:55 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.1.2-1
- Initial package
