# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate fern

Name:           rust-%{crate}
Version:        0.5.8
Release:        1%{?dist}
Summary:        Simple, efficient logging

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/fern
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(log/std) >= 0.4.0 with crate(log/std) < 0.5.0)
%if %{with check}
BuildRequires:  (crate(chrono/default) >= 0.4.0 with crate(chrono/default) < 0.5.0)
BuildRequires:  (crate(clap/default) >= 2.22.0 with crate(clap/default) < 3.0.0)
BuildRequires:  (crate(tempdir/default) >= 0.3.0 with crate(tempdir/default) < 0.4.0)
%endif
%endif

%global _description %{expand:
Simple, efficient logging.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+colored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+colored-devel %{_description}

This package contains library source intended for building other packages
which use "colored" feature of "%{crate}" crate.

%files       -n %{name}+colored-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+meta-logging-in-format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+meta-logging-in-format-devel %{_description}

This package contains library source intended for building other packages
which use "meta-logging-in-format" feature of "%{crate}" crate.

%files       -n %{name}+meta-logging-in-format-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+syslog-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syslog-devel %{_description}

This package contains library source intended for building other packages
which use "syslog" feature of "%{crate}" crate.

%files       -n %{name}+syslog-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+syslog-3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syslog-3-devel %{_description}

This package contains library source intended for building other packages
which use "syslog-3" feature of "%{crate}" crate.

%files       -n %{name}+syslog-3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+syslog-4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syslog-4-devel %{_description}

This package contains library source intended for building other packages
which use "syslog-4" feature of "%{crate}" crate.

%files       -n %{name}+syslog-4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+syslog3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syslog3-devel %{_description}

This package contains library source intended for building other packages
which use "syslog3" feature of "%{crate}" crate.

%files       -n %{name}+syslog3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 00:47:27 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.5.8-1
- Initial package
