# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate svgparser

Name:           rust-%{crate}
Version:        0.6.4
Release:        1%{?dist}
Summary:        Featureful, pull-based, zero-allocation SVG parser

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            https://crates.io/crates/svgparser
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(error-chain) >= 0.11.0 with crate(error-chain) < 0.12.0)
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(phf/default) >= 0.7.21 with crate(phf/default) < 0.8.0)
BuildRequires:  (crate(xmlparser/default) >= 0.1.0 with crate(xmlparser/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(bencher/default) >= 0.1.0 with crate(bencher/default) < 0.2.0)
BuildRequires:  (crate(stderrlog/default) >= 0.2.0 with crate(stderrlog/default) < 0.3.0)
%endif
%endif

%global _description %{expand:
Featureful, pull-based, zero-allocation SVG parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 01:14:36 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.6.4-1
- Initial package
