# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate textwrap

Name:           rust-%{crate}
Version:        0.11.0
Release:        1%{?dist}
Summary:        Small library for word wrapping, indenting, and dedenting strings

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/textwrap
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(unicode-width/default) >= 0.1.3 with crate(unicode-width/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(lipsum/default) >= 0.6.0 with crate(lipsum/default) < 0.7.0)
BuildRequires:  (crate(rand/default) >= 0.6.0 with crate(rand/default) < 0.7.0)
BuildRequires:  (crate(rand_xorshift/default) >= 0.1.0 with crate(rand_xorshift/default) < 0.2.0)
BuildRequires:  (crate(version-sync/default) >= 0.6.0 with crate(version-sync/default) < 0.7.0)
%endif
%endif

%global _description %{expand:
Small library for word wrapping, indenting, and dedenting strings.
You can use it to format strings (such as help and error messages) for display
in commandline applications. It is designed to be efficient and handle Unicode
characters correctly.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hyphenation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyphenation-devel %{_description}

This package contains library source intended for building other packages
which use "hyphenation" feature of "%{crate}" crate.

%files       -n %{name}+hyphenation-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+term_size-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+term_size-devel %{_description}

This package contains library source intended for building other packages
which use "term_size" feature of "%{crate}" crate.

%files       -n %{name}+term_size-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 00:48:46 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.11.0-1
- Initial package
