# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate svgdom

Name:           rust-%{crate}
Version:        0.10.5
Release:        1%{?dist}
Summary:        Library to represent an SVG as a DOM

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            https://crates.io/crates/svgdom
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(error-chain) >= 0.11.0 with crate(error-chain) < 0.12.0)
BuildRequires:  (crate(float-cmp/default) >= 0.3.0 with crate(float-cmp/default) < 0.4.0)
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(simplecss/default) >= 0.1.0 with crate(simplecss/default) < 0.2.0)
BuildRequires:  (crate(svgparser/default) >= 0.6.0 with crate(svgparser/default) < 0.7.0)
%if %{with check}
BuildRequires:  (crate(bencher/default) >= 0.1.0 with crate(bencher/default) < 0.2.0)
BuildRequires:  (crate(time/default) >= 0.1.0 with crate(time/default) < 0.2.0)
%endif
%endif

%global _description %{expand:
Library to represent an SVG as a DOM.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 01:21:30 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.10.5-1
- Initial package
