# Generated by rust2rpm 16
%bcond_without check

%global crate svgcleaner

Name:           rust-%{crate}
Version:        0.9.5
Release:        1%{?dist}
Summary:        Svgcleaner could help you to clean up your SVG files from the unnecessary data

# Upstream license specification: GPL-2.0
License:        GPLv2
URL:            https://crates.io/crates/svgcleaner
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(clap) >= 2.0.0 with crate(clap) < 3.0.0)
BuildRequires:  (crate(error-chain) >= 0.11.0 with crate(error-chain) < 0.12.0)
BuildRequires:  (crate(fern/default) >= 0.5.0 with crate(fern/default) < 0.6.0)
BuildRequires:  (crate(log/default) >= 0.4.0 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(svgdom/default) >= 0.10.5 with crate(svgdom/default) < 0.11.0)
%endif

%global _description %{expand:
Svgcleaner could help you to clean up your SVG files from the unnecessary data.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.rst
%{_bindir}/svgcleaner
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.rst
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages
which use "clap" feature of "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+cli-parsing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cli-parsing-devel %{_description}

This package contains library source intended for building other packages
which use "cli-parsing" feature of "%{crate}" crate.

%files       -n %{name}+cli-parsing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 01:23:06 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.9.5-1
- Initial package
