# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate float-cmp

Name:           rust-%{crate}
Version:        0.3.0
Release:        1%{?dist}
Summary:        Floating point approximate comparison traits

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/float-cmp
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(num) >= 0.1.0 with crate(num) < 0.2.0)
%endif

%global _description %{expand:
Floating point approximate comparison traits.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 01:17:10 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.3.0-1
- Initial package
