# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate log

Name:           rust-%{crate}
Version:        0.4.8
Release:        1%{?dist}
Summary:        Lightweight logging facade for Rust

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/log
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(cfg-if/default) >= 0.1.2 with crate(cfg-if/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(serde_test/default) >= 1.0.0 with crate(serde_test/default) < 2.0.0)
BuildRequires:  (crate(sval/default) >= 0.4.2 with crate(sval/default) < 0.5.0)
BuildRequires:  (crate(sval/test) >= 0.4.2 with crate(sval/test) < 0.5.0)
%endif
%endif

%global _description %{expand:
Lightweight logging facade for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+kv_unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+kv_unstable-devel %{_description}

This package contains library source intended for building other packages
which use "kv_unstable" feature of "%{crate}" crate.

%files       -n %{name}+kv_unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+kv_unstable_sval-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+kv_unstable_sval-devel %{_description}

This package contains library source intended for building other packages
which use "kv_unstable_sval" feature of "%{crate}" crate.

%files       -n %{name}+kv_unstable_sval-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_debug-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_debug" feature of "%{crate}" crate.

%files       -n %{name}+max_level_debug-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_error-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_error" feature of "%{crate}" crate.

%files       -n %{name}+max_level_error-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_info-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_info" feature of "%{crate}" crate.

%files       -n %{name}+max_level_info-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_off-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_off" feature of "%{crate}" crate.

%files       -n %{name}+max_level_off-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_trace-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_trace" feature of "%{crate}" crate.

%files       -n %{name}+max_level_trace-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_warn-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_warn" feature of "%{crate}" crate.

%files       -n %{name}+max_level_warn-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_debug-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_debug" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_debug-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_error-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_error" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_error-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_info-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_info" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_info-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_off-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_off" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_off-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_trace-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_trace" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_trace-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+release_max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_warn-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_warn" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_warn-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sval-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sval-devel %{_description}

This package contains library source intended for building other packages
which use "sval" feature of "%{crate}" crate.

%files       -n %{name}+sval-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 00:24:37 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.4.8-1
- Initial package
