# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate num

Name:           rust-%{crate}
Version:        0.1.42
Release:        1%{?dist}
Summary:        Collection of numeric types and traits for Rust, including bigint, complex, rational, range iterators, generic integers, and more!

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/num
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if ! %{__cargo_skip_build}
BuildRequires:  (crate(num-integer/default) >= 0.1.36 with crate(num-integer/default) < 0.2.0)
BuildRequires:  (crate(num-iter/default) >= 0.1.35 with crate(num-iter/default) < 0.2.0)
BuildRequires:  (crate(num-traits/default) >= 0.2.0 with crate(num-traits/default) < 0.3.0)
%endif

%global _description %{expand:
Collection of numeric types and traits for Rust, including bigint, complex,
rational, range iterators, generic integers, and more!.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build -- --no-default-features

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 14 00:59:57 MSK 2021 Yaroslav Sidlovsky <zawertun@gmail.com> - 0.1.42-1
- Initial package
